### ISSUE TITLE
shout

### ISSUE THREAD

**Issue by Konfekt** [ShayHill/vim9-scratchterm#1]
It seems that https://github.com/habamax/vim-shout and your plug-in have similar ends but different means.
Maybe you could add a note on why the former did not suffice your exact ends

**Comment by ShayHill** [comment]
Thank you. I will have a look.

On Jun 25, 2024, at 01:11, Enno ***@***.***> wrote:

﻿

It seems that https://github.com/habamax/vim-shout and your plug-in have similar ends but different means.
Maybe you could add a note on why the former did not suffice your exact ends

**Comment by ShayHill** [comment]
I added a note to the readme file. Thank you.
